// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package network

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Envelope struct {
	_tab flatbuffers.Table
}

func GetRootAsEnvelope(buf []byte, offset flatbuffers.UOffsetT) *Envelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Envelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEnvelope(buf []byte, offset flatbuffers.UOffsetT) *Envelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Envelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Envelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Envelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Envelope) MsgType() NetworkUnion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return NetworkUnion(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Envelope) MutateMsgType(n NetworkUnion) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Envelope) Msg(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func EnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EnvelopeAddMsgType(builder *flatbuffers.Builder, msgType NetworkUnion) {
	builder.PrependByteSlot(0, byte(msgType), 0)
}
func EnvelopeAddMsg(builder *flatbuffers.Builder, msg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(msg), 0)
}
func EnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
