// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package network

import "strconv"

type NetworkUnion byte

const (
	NetworkUnionNONE    NetworkUnion = 0
	NetworkUnionRequest NetworkUnion = 1
)

var EnumNamesNetworkUnion = map[NetworkUnion]string{
	NetworkUnionNONE:    "NONE",
	NetworkUnionRequest: "Request",
}

var EnumValuesNetworkUnion = map[string]NetworkUnion{
	"NONE":    NetworkUnionNONE,
	"Request": NetworkUnionRequest,
}

func (v NetworkUnion) String() string {
	if s, ok := EnumNamesNetworkUnion[v]; ok {
		return s
	}
	return "NetworkUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
