// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package network

import "strconv"

type Package int8

const (
	PackageInit            Package = 0
	PackagePending         Package = 1
	PackageCloseConnection Package = 2
	PackageMessage         Package = 3
)

var EnumNamesPackage = map[Package]string{
	PackageInit:            "Init",
	PackagePending:         "Pending",
	PackageCloseConnection: "CloseConnection",
	PackageMessage:         "Message",
}

var EnumValuesPackage = map[string]Package{
	"Init":            PackageInit,
	"Pending":         PackagePending,
	"CloseConnection": PackageCloseConnection,
	"Message":         PackageMessage,
}

func (v Package) String() string {
	if s, ok := EnumNamesPackage[v]; ok {
		return s
	}
	return "Package(" + strconv.FormatInt(int64(v), 10) + ")"
}
